START TRANSACTION;
ALTER TABLE `#__prj_exp` DROP `curatorID`;
ALTER TABLE `#__prj_exp` CHANGE `regID` `regID` INT(11) UNSIGNED NOT NULL COMMENT 'ID региона';
ALTER TABLE `#__prj_exp` ADD FOREIGN KEY (`regID`) REFERENCES `#__grph_cities`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `#__prj_contracts` CHANGE `managerID` `managerID` INT(11) NOT NULL COMMENT 'ID руководителя';
ALTER TABLE `#__prj_contracts` ADD `groupID` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Проектная группа менеджеров' AFTER `managerID`, ADD INDEX (`groupID`);
ALTER TABLE `#__prj_contracts` ADD FOREIGN KEY (`groupID`) REFERENCES `#__usergroups`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `#__prj_contracts` CHANGE `managerID` `managerID` INT(11) NULL DEFAULT NULL COMMENT 'ID руководителя';
ALTER TABLE `#__prj_contracts` DROP INDEX `prjID`, ADD INDEX `prjID` (`prjID`) USING BTREE;
ALTER TABLE `#__prj_contracts` ADD `state` TINYINT NOT NULL DEFAULT '0' AFTER `status`;
ALTER TABLE `#__prj_contracts` ADD `number` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Номер договора' AFTER `status`;
COMMIT;
