START TRANSACTION;
ALTER TABLE `#__prj_exp` DROP `curatorID`;
ALTER TABLE `#__prj_exp` CHANGE `regID` `regID` INT(11) UNSIGNED NOT NULL COMMENT 'ID региона';
ALTER TABLE `#__prj_exp` ADD FOREIGN KEY (`regID`) REFERENCES `#__grph_cities`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
COMMIT;
